server:
  port: 8085

spring:
  cloud:
    discovery:
      enabled: false
    function:
      definition: dataConsumer
    stream:
      rabbit:
        bindings:
          dataConsumer-in-0:
            destination: local.exchange
            consumer:
              bindQueue: true
              queueNameGroupOnly: true
              declareExchange: false
              bindingRoutingKey: smfexportconsumer
              exchangeDurable: true
             # maxConcurrency: 5
      function:
        bindings:
          dataConsumer-in-0:
            destination: local.exchange
      bindings:
        dataConsumer-in-0:
          group: smfexportconsumer
  rabbitmq.addresses: amqp://guest:guest@localhost/

logging:
  level:
    reactor:
      netty: debug

